---
version: "2.1"
services:
  irixenv:
    image: irixenv:latest
    container_name: irixenv
    healthcheck:
      disable: true
    ports:
      - 3632:3632
      - 8186:8186
    # Uncomment these two lines to set up a local cross compilation env
    #volumes:
    #  - /opt/irix:/opt/irix


