---
version: '3'

# networks:
#   internalnet:

services:
  compilertron:
    image: unxmaal/compilertron:latest
    container_name: compilertron
    hostname: compilertron
    ports:
      - "8086:8086"
      - "8186:8186"
      - "3632:3632"
    # networks:
    #   - internalnet
