---
version: "2.1"
services:
  compilertron:
    image: unxmaal/compilertron:latest
    container_name: compilertron
    healthcheck:
      disable: true
    ports:
      - 3632:3632
      - 8186:8186
# Uncomment the next two lines to set up a local cross compilation env.  Make sure /opt/irix exists.
#    volumes:
#      - /opt/irix:/opt/irix

# Note: it _must_ be /opt/irix, though you can map /foo/cheeseburger:/opt/irix as long as you also make a local
# /opt/irix -> /foo/cheeseburger symlink
